### ISSUE TITLE
Clear test is not working properly

### ISSUE THREAD

**Issue by anykeyh** [jwoertink/crystal_orm_test#1]
Hello !

I drop randomly on this page and I found that clear is super fast compare to other ORM. Well, as the creator, I was a bit curious at first, but I noticed it does not insert value in the database.

`save` will return `false`, as your fields `created_at` and `updated_at` are of type `Time`, but you set no value (so presence validation will fail).

In this case, you should add `presence: false`:

```crystal
    column created_at : Time, presence: false
    column updated_at : Time, presence: false
```

This would then works properly.
Also, note than calling `save!` should raise an error and not silently fail like here.

**Comment by jwoertink** [comment]
Ah, good catch! I didn't realize it was doing validation automatically. I'll update that. Thanks 😂
